routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SearchController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class,'index'])->name('home');
Route::resource('categories',CategoryController::class);
Route::resource('products',ProductController::class);
Route::resource('carts',CartController::class);

Route::get('/searchs',[SearchController::class,'index'])->name('searchs.index');

resources/views/partials/cards.blade.php
<div class="card me-5 mb-5 mycards" style="width: 18rem">
    <img
        src="{{$product->image}}"
        alt="{{$product->title}}"
    />
    <div class="card-body d-flex flex-column justify-content-between">
        <h5 class="card-title">{{$product->title}}</h5>
        <p class="card-text">{{substr($product->description,0,100)}}...</p>
        <h5 class="card-title">{{$product->price}}</h5>
        <form method="post" action="{{ route('carts.store') }}">
            @csrf
            <input type="hidden" name="product_id" value="{{$product->id}}" />
            <button class="btn btn-primary">Add to shop cart</button>
        </form>
    </div>
</div>

resources/views/partials/form_success.blade.php
@if(session('message'))
<div class="alert alert-success" role="alert">
    {!!session('message')!!}
</div>
@endif

resources/views/partials/navBar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
    <a class="navbar-brand" href="{{route('home')}}">LaraShopping</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link {{Request::path()=='/' ?'active':''}}" aria-current="page" href="{{route('home')}}">Home</a>
        </li>
        @foreach ($categories as $category)
            <li class="nav-item">
                <a class="nav-link {{Request::path()=='categories/'.$category->id ?'active':''}}" href="{{route('categories.show',$category)}}">{{$category->name}}</a>
        </li>
        @endforeach
        </ul>
        <ul class="navbar-nav mb-2 me-3 mb-lg-0">
            <li class="nav-item me-4 nav-link">{{$carts->sum('quantity')}} items / Total:@include('partials.total')$</li>
            <li class="nav-item"><a href="{{route('carts.index')}}" class="nav-link {{Request::path()=='carts' ?'active':''}}" aria-current="page">Cart</a></li>
        </ul>
        <form class="d-flex" action="{{route('searchs.index')}}" role="search">
            <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-light">Search</button>
        </form>
    </div>
</nav>

resources/views/partials/total.blade.php
<?php 
    $total=0;
?>
@foreach($carts as $cart)
  <?php
    $total += ($cart->product->price*$cart->quantity);
  ?>
@endforeach
{{$total}}