routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SearchController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class,'index'])->name('home');
Route::resource('categories',CategoryController::class);
Route::resource('products',ProductController::class);
Route::resource('carts',CartController::class);

Route::get('/searchs',[SearchController::class,'index'])->name('searchs.index');

app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Type\Integer;

class Cart extends Model
{
    use HasFactory;

    protected $fillable=['product_id'];
    public function product(){
        return $this->belongsTo(Product::class);
    } 
    public function totalPrice($price,$quantity){
        $total=$price*$quantity;
        return $total;
    }
    public function endprice(){
        $total=0;
        for($i=0;$i<$this->count();$i++){
            $total+=$this->product->price*$this->quantity;
        }
        return $this->belongsTo(Product::class)->$total;
    }
}

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cart;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Symfony\Component\Console\Input\Input;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $carts=Cart::all();
        $categories=Category::all();
        $products=Product::all();
        $quantity=$request->input('quantity');
        
        return view('carts.index',compact('carts','products','categories','quantity'));
    }
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated=$request->validate([
            'product_id' => 'required | exists:products,id',
        ]);
        if(Cart::where('product_id',$validated['product_id'])->exists()){
            Cart::where('product_id',$validated['product_id'])->increment('quantity');
        }
       else{
        Cart::create([
        'product_id' => $validated['product_id'],
       ]);
        }
       return redirect(route('carts.index'))->with('message',"Product added successfully");
    }

    /**
     * Display the specified resource.
     */
    public function show(Cart $cart)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Cart $cart)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Cart $cart)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Cart $cart)
    {
        $cart->delete();
        $product=$cart->product;
        return redirect(route('carts.index'))->with('message',"Product <strong>$product->title</strong> deleted from cart!");
    }
}

resources/views/carts/index.blade.php
@extends('layouts.app')

@section('head_title','Shopping cart')

@section('content')
    <h1>Cart</h1>
   @include('partials.form_success')
    @if($carts->count()<=0)
        <h1>Empty</h1>
    @else
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>Delete</th>
                <th >#</th>
                <th >Title</th>
                <th >Price</th>
                <th>Qty</th>
                <th >Total</th>
            </tr>
            </thead>
            <tbody>
                @foreach($carts as $i=>$cart)
                <tr>
                    <td>
                        <form method="post" action="{{route('carts.destroy',$cart)}}" id="">
                        @method('delete')
                        @csrf
                        <button class="btn btn-danger confirm_delete">X</button>
                        </form>
                    </td>
                    <th scope>{{$i+1}}</th>
                    <th scope>{{$cart->product->title}}</th>
                    <td>{{$cart->product->price}}</td>
                    <td><input type="text" value="{{$cart->quantity}}" name="quantity"></td>
                    <td>{{$cart->totalPrice($cart->product->price,$cart->quantity)}}</td>
                </tr>
                @endforeach
                <tr>
                    <td colspan="4"></td>
                    <td>{{$cart->sum('quantity')}}</td>
                    <td>
                        @include('partials.total')
                    </td>
                </tr>
            </tbody>
        </table>
    @endif
    <script>
        $('.confirm_delete').click(e=>{
          if(!confirm('are you sure?')){
            e.preventDefault();
          }
        });
    </script>
@endsection